#!/bin/bash
set +e
export NVM_DIR="$HOME/.nvm"

if [ -e "$NVM_DIR" ]; then
  echo "NVM is already installed skipping"
else
  touch ~/.profile

  set +e
  mkdir $HOME/.nvm
  curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v$NVM_VERSION/install.sh | bash
  set -e

fi

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion